### ISSUE TITLE
Can't find that library

### ISSUE THREAD

**Issue by kjones1807** [davekch/linerizer#1]
I couldn't find the "linerizer" library, but I did find the drop library and I don't know how to use it. Please help!

**Comment by davekch** [comment]
Hi, if you have Processing and the drop library ready, you can open the file [linerizer.pde](https://github.com/davekch/linerizer/blob/master/linerizer.pde) (download it from this repository) in Processing and hit "Run".

**Comment by gijdoul** [comment]
How to run it on Mac ?

**Comment by gijdoul** [comment]
I make it work but get issue line 19 I comment  //size(500, 100); and it work but don't know how to export the result ?

**Comment by davekch** [comment]
Can you post the error message you got? I can't reproduce the issue.

As for exporting, the program does not provide any way to export the result. You can however make a screenshot.

**Comment by gijdoul** [comment]
Hello here the error message:

When not using the PDE, size() can only be used inside settings().
Remove the size() method from setup(), and add the following:
public void settings() {
IllegalStateException: size() cannot be used here, see https://processing.org/reference/size_.html
  size(500, 100);
}

**Comment by davekch** [comment]
Thanks. It seems you have the issue described [here](https://github.com/processing/processing/issues/5759). Make sure to use Processing version 3.5.1 or newer.
